import {
  Profile,
  Lead,
  FollowUp,
  ActivityLog,
  WhatsAppTemplate,
  SlaSettings,
  AppNotification,
  IncentiveTier,
} from '../types';

// Deterministic UTC baseline time for demo data to avoid hydration mismatches between SSR and Client
const FIXED_BASE_TIME = 1789128000000; // 2026-09-11T12:00:00.000Z

export const INITIAL_PROFILES: Profile[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    employee_code: 'TRV-ADM-001',
    email: 'admin@travellms.com',
    full_name: 'Sarah Jenkins',
    role: 'admin',
    phone: '+1 415 555 0100',
    direct_extension: 'Ext. 101',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    destination_tags: ['Global', 'VIP Luxury', 'Executive'],
    max_capacity: 50,
    current_load: 0,
    status: 'available',
    is_active: true,
    accepting_leads: false,
    bio: 'Agency founder & operations head. Oversees company-wide SLAs, global vendor contracts, and premium client escalations.',
    languages: ['English', 'Spanish'],
    office_location: 'San Francisco HQ',
    certifications: ['IATA Travel Executive', 'Virtuoso Certified Advisor'],
    created_at: new Date(FIXED_BASE_TIME - 30 * 86400000).toISOString(),
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    employee_code: 'TRV-MGR-002',
    email: 'manager@travellms.com',
    full_name: 'David Miller',
    role: 'manager',
    phone: '+1 415 555 0101',
    direct_extension: 'Ext. 102',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    destination_tags: ['All Teams', 'Escalations', 'Group Charters'],
    max_capacity: 40,
    current_load: 0,
    status: 'available',
    is_active: true,
    accepting_leads: false,
    bio: 'Sales Director overseeing consultant performance, round-robin lead allocation, and monthly profit margins.',
    languages: ['English', 'German'],
    office_location: 'San Francisco HQ',
    certifications: ['Certified Travel Industry Leader', 'Cruises & Groups Master'],
    created_at: new Date(FIXED_BASE_TIME - 25 * 86400000).toISOString(),
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    employee_code: 'TRV-AGT-003',
    email: 'alex@travellms.com',
    full_name: 'Alex Rivera',
    role: 'agent',
    phone: '+1 415 555 0102',
    direct_extension: 'Ext. 103',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    destination_tags: ['Bali', 'Thailand', 'Vietnam', 'Singapore', 'Asia'],
    max_capacity: 25,
    current_load: 4,
    status: 'available',
    is_active: true,
    accepting_leads: true,
    bio: 'Southeast Asia specialist focusing on luxury honeymoons, private villa stays in Ubud & Seminyak, and exotic multi-city tours.',
    languages: ['English', 'Spanish', 'Indonesian (Basic)'],
    office_location: 'Remote - West Coast',
    certifications: ['Wonderful Indonesia Certified Specialist', 'Thailand Tourism Board Expert'],
    created_at: new Date(FIXED_BASE_TIME - 20 * 86400000).toISOString(),
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    employee_code: 'TRV-AGT-004',
    email: 'emma@travellms.com',
    full_name: 'Emma Watson',
    role: 'agent',
    phone: '+1 415 555 0103',
    direct_extension: 'Ext. 104',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    destination_tags: ['Switzerland', 'Paris', 'Italy', 'Europe', 'Greece'],
    max_capacity: 25,
    current_load: 3,
    status: 'in_call',
    is_active: true,
    accepting_leads: true,
    bio: 'European grand tour curator. Specializes in Swiss panoramic trains, romantic Parisian boutique getaways, and Amalfi Coast charters.',
    languages: ['English', 'French', 'Italian'],
    office_location: 'Remote - East Coast',
    certifications: ['Switzerland Travel Academy Gold', 'France Destination Specialist'],
    created_at: new Date(FIXED_BASE_TIME - 20 * 86400000).toISOString(),
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    employee_code: 'TRV-AGT-005',
    email: 'michael@travellms.com',
    full_name: 'Michael Chang',
    role: 'agent',
    phone: '+1 415 555 0104',
    direct_extension: 'Ext. 105',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    destination_tags: ['Dubai', 'Maldives', 'Mauritius', 'Egypt', 'Middle East'],
    max_capacity: 25,
    current_load: 3,
    status: 'available',
    is_active: true,
    accepting_leads: true,
    bio: 'Middle East & Indian Ocean bespoke designer. Expert in overwater Maldives resorts, Dubai desert glamping, and private Nile River cruises.',
    languages: ['English', 'Mandarin', 'Arabic (Basic)'],
    office_location: 'San Francisco HQ',
    certifications: ['Dubai Expert Plus', 'Maldives Border Miles Partner'],
    created_at: new Date(FIXED_BASE_TIME - 15 * 86400000).toISOString(),
  },
];

export const INITIAL_INCENTIVE_TIERS: IncentiveTier[] = [
  {
    id: 'tier-bronze',
    name: 'Bronze Tier',
    min_sales: 0,
    max_sales: 5000,
    commission_pct_profit: 6,
    milestone_bonus: 0,
    min_margin_threshold: 10,
  },
  {
    id: 'tier-silver',
    name: 'Silver Tier',
    min_sales: 5000,
    max_sales: 12000,
    commission_pct_profit: 9,
    milestone_bonus: 150,
    min_margin_threshold: 10,
  },
  {
    id: 'tier-gold',
    name: 'Gold Tier',
    min_sales: 12000,
    max_sales: 25000,
    commission_pct_profit: 13,
    milestone_bonus: 350,
    min_margin_threshold: 10,
  },
  {
    id: 'tier-platinum',
    name: 'Platinum Top-Gun',
    min_sales: 25000,
    max_sales: null,
    commission_pct_profit: 18,
    milestone_bonus: 750,
    min_margin_threshold: 12,
  },
];

const now = FIXED_BASE_TIME;
const min = 60 * 1000;
const hour = 60 * min;
const day = 24 * hour;

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'a1111111-0000-0000-0000-000000000001',
    lead_code: 'TRV-2026-0001',
    customer_name: 'Rohan Sharma',
    customer_email: 'rohan.sharma@gmail.com',
    customer_phone: '+919876543210',
    customer_city: 'Mumbai',
    customer_country: 'India',
    destination: 'Bali',
    travel_dates: '2026-11-10 to 2026-11-17',
    duration_days: 7,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'honeymoon',
    budget_range: '$2,000 - $3,000',
    hotel_category: '5-star',
    flight_required: true,
    visa_required: true,
    special_notes: 'Wants private pool villa in Seminyak and Ubud swing day tour.',
    source: 'website',
    stage: 'quote_sent',
    priority: 'urgent',
    package_sale_price: 2800,
    vendor_net_cost: 2350,
    gross_profit: 450,
    profit_margin_pct: 16.1,
    agent_commission_earned: 40.5,
    trip_status: 'planning',
    payment_milestones: [
      {
        id: 'ms-1',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        title: 'Booking Deposit (25%)',
        percentage: 25,
        amount: 700,
        due_date: '2026-10-01',
        status: 'paid',
        paid_amount: 700,
        paid_at: new Date(now - 3 * day).toISOString(),
        notes: 'Deposit to lock private pool villa rate',
      },
      {
        id: 'ms-2',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        title: 'Mid-Term Advance (50%)',
        percentage: 50,
        amount: 1400,
        due_date: '2026-10-20',
        status: 'pending',
        paid_amount: 0,
        notes: 'Required 20 days prior to airline ticket release',
      },
      {
        id: 'ms-3',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        title: 'Final Balance (25%)',
        percentage: 25,
        amount: 700,
        due_date: '2026-11-01',
        status: 'pending',
        paid_amount: 0,
        notes: 'Settled upon release of hotel vouchers and DMC driver details',
      },
    ],
    payment_records: [
      {
        id: 'pay-rec-1',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        receipt_number: 'REC-2026-1049',
        amount: 700,
        method: 'bank_transfer',
        reference_no: 'HDFC-WIRE-9921',
        notes: 'Client confirmed transfer from HDFC account',
        received_at: new Date(now - 3 * day).toISOString(),
        created_at: new Date(now - 3 * day).toISOString(),
      },
    ],
    itinerary_days: [
      {
        id: 'day-1',
        day_number: 1,
        title: 'Denpasar DPS Arrival & Ubud Rainforest Villa Transfer',
        description: 'VIP airport fast-track reception followed by private scenic transfer through Gianyar rice fields into the heart of Ubud.',
        hotel_name: 'Kamandalu Resort Ubud (Valley Pool Villa)',
        meal_plan: 'CP',
        morning_activity: 'VIP Airport Meet & Greet with cold towel service',
        afternoon_activity: 'Private AC transfer and Ubud village arrival',
        evening_activity: 'Check-in at pool villa followed by candlelight welcome dinner',
        activities: [
          'VIP Airport Fast-track greeting at Denpasar DPS',
          'Private air-conditioned transfer with local driver',
          'Check-in at Valley Pool Villa with floral welcome',
          'Candlelight 3-course Balinese welcome dinner',
        ],
      },
      {
        id: 'day-2',
        day_number: 2,
        title: 'Kintamani Volcano Sunrise, Rice Terraces & Holy Spring Blessing',
        description: 'Panoramic sunrise vista over Mount Batur volcano, followed by thrilling jungle swing experience and spiritual water blessing.',
        hotel_name: 'Kamandalu Resort Ubud',
        meal_plan: 'MAP',
        morning_activity: 'Mount Batur volcano viewpoint breakfast',
        afternoon_activity: 'Tegalalang jungle swing & Luwak coffee tasting',
        evening_activity: 'Tirta Empul ancient temple blessing ritual',
        activities: [
          'Mount Batur volcano caldera viewpoint breakfast',
          'Tegalalang terraced rice field walk and jungle swing',
          'Luwak coffee plantation roast demonstration and tasting',
          'Tirta Empul sacred water temple purification ritual',
        ],
      },
      {
        id: 'day-3',
        day_number: 3,
        title: 'Ubud to Seminyak Luxury Coastal Transfer & Sunset Lounge',
        description: 'Transition from lush highlands to southern beaches with afternoon relaxation and front-row sunset seats.',
        hotel_name: 'W Bali Seminyak (Ocean Facing Haven)',
        meal_plan: 'CP',
        morning_activity: 'Floating breakfast at private villa pool',
        afternoon_activity: 'Coastal transfer & Seminyak boutique shopping',
        evening_activity: 'Sunset cocktails at Potato Head Beach Club',
        activities: [
          'Private pool floating breakfast with tropical fruit platter',
          'Chauffeured transfer from Ubud to Seminyak beach strip',
          'Hotel check-in and beach stroll',
          'Reserved sunbed and sunset cocktails at Potato Head',
        ],
      },
    ],
    passengers: [
      {
        id: 'pax-1',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        full_name: 'Rohan Sharma',
        type: 'adult',
        passport_number: 'Z5928192',
        passport_country: 'India',
        passport_expiry_date: '2029-08-14',
        is_passport_valid_6months: true,
        visa_status: 'visa_on_arrival',
        date_of_birth: '1992-06-15',
        dietary_preference: 'Vegetarian',
        special_notes: 'Wants aisle seat on international flight segments',
      },
      {
        id: 'pax-2',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        full_name: 'Priya Sharma',
        type: 'adult',
        passport_number: 'Z5928193',
        passport_country: 'India',
        passport_expiry_date: '2029-05-20',
        is_passport_valid_6months: true,
        visa_status: 'visa_on_arrival',
        date_of_birth: '1994-11-22',
        dietary_preference: 'Vegetarian',
        special_notes: 'Honeymoon cake requested at hotel check-in',
      },
    ],
    documents: [
      {
        id: 'doc-1',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        title: 'Rohan Sharma - Passport Scan',
        category: 'passport',
        file_name: 'rohan_passport_front.pdf',
        file_size: '1.2 MB',
        uploaded_at: new Date(now - 2 * day).toISOString(),
      },
      {
        id: 'doc-2',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        title: 'Flight E-Tickets (BOM-DPS Return)',
        category: 'ticket',
        file_name: 'singapore_airlines_eticket.pdf',
        file_size: '840 KB',
        uploaded_at: new Date(now - 1 * day).toISOString(),
      },
    ],
    supplier_payables: [
      {
        id: 'sp-1',
        lead_id: 'a1111111-0000-0000-0000-000000000001',
        supplier_name: 'Bali Sun DMC & Ground Operators',
        service_description: '7D private AC vehicle + airport transfers + Ubud swing tour',
        amount_payable: 850,
        amount_paid: 350,
        status: 'advance_paid',
        confirmation_voucher_no: 'VOUCH-BALI-8821',
        due_date: '2026-10-25',
      },
    ],
    checklist: {
      flights_ticketed: true,
      hotel_vouchers_issued: true,
      passports_verified_6months: true,
      visas_confirmed: true,
      travel_insurance_issued: false,
      web_checkin_completed: false,
      emergency_contacts_dispatched: true,
    },
    assigned_to: '33333333-3333-3333-3333-333333333333', // Alex
    assigned_at: new Date(now - 14 * min).toISOString(),
    first_response_due_at: new Date(now + 16 * min).toISOString(),
    is_first_response_breached: false,
    next_follow_up_at: new Date(now + 16 * min).toISOString(),
    created_at: new Date(now - 14 * min).toISOString(),
    updated_at: new Date(now - 14 * min).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000002',
    lead_code: 'TRV-2026-0002',
    customer_name: 'Jessica Taylor',
    customer_email: 'jessica.t@outlook.com',
    customer_phone: '+14155552345',
    customer_city: 'San Francisco',
    customer_country: 'USA',
    destination: 'Switzerland',
    travel_dates: '2026-12-20 to 2026-12-28',
    duration_days: 8,
    pax_adults: 2,
    pax_children: 2,
    pax_infants: 0,
    travel_type: 'family',
    budget_range: '$6,000 - $8,000',
    hotel_category: '4-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Christmas ski trip, Zermatt & Interlaken, Swiss Travel Pass inquiry.',
    source: 'meta_ads',
    stage: 'won',
    priority: 'high',
    package_sale_price: 7400,
    vendor_net_cost: 6100,
    gross_profit: 1300,
    profit_margin_pct: 17.5,
    agent_commission_earned: 117.0,
    commission_status: 'approved',
    trip_status: 'pre_departure',
    passengers: [
      {
        id: 'pax-jt-1',
        lead_id: 'a1111111-0000-0000-0000-000000000002',
        full_name: 'Jessica Taylor',
        type: 'adult',
        passport_number: 'US88291049',
        passport_country: 'USA',
        passport_expiry_date: '2028-11-12',
        is_passport_valid_6months: true,
        visa_status: 'not_required',
      },
      {
        id: 'pax-jt-2',
        lead_id: 'a1111111-0000-0000-0000-000000000002',
        full_name: 'Mark Taylor',
        type: 'adult',
        passport_number: 'US88291050',
        passport_country: 'USA',
        passport_expiry_date: '2026-11-01',
        is_passport_valid_6months: false,
        visa_status: 'not_required',
        special_notes: 'Urgent passport renewal application in progress with US State Dept',
      },
      {
        id: 'pax-jt-3',
        lead_id: 'a1111111-0000-0000-0000-000000000002',
        full_name: 'Chloe Taylor',
        type: 'child',
        passport_number: 'US88291051',
        passport_country: 'USA',
        passport_expiry_date: '2029-04-10',
        is_passport_valid_6months: true,
        visa_status: 'not_required',
      },
      {
        id: 'pax-jt-4',
        lead_id: 'a1111111-0000-0000-0000-000000000002',
        full_name: 'Leo Taylor',
        type: 'child',
        passport_number: 'US88291052',
        passport_country: 'USA',
        passport_expiry_date: '2029-04-10',
        is_passport_valid_6months: true,
        visa_status: 'not_required',
      },
    ],
    checklist: {
      flights_ticketed: true,
      hotel_vouchers_issued: true,
      passports_verified_6months: false,
      visas_confirmed: true,
      travel_insurance_issued: true,
      web_checkin_completed: false,
      emergency_contacts_dispatched: false,
    },
    supplier_payables: [
      {
        id: 'sp-2',
        lead_id: 'a1111111-0000-0000-0000-000000000002',
        supplier_name: 'Swiss Alps Luxury DMC',
        service_description: 'Zermatt ski passes + Gornergrat cogwheel train + 7N chalet',
        amount_payable: 3200,
        amount_paid: 3200,
        status: 'settled',
        confirmation_voucher_no: 'VOUCH-CH-9941',
        due_date: '2026-11-15',
      },
    ],
    assigned_to: '44444444-4444-4444-4444-444444444444', // Emma
    assigned_at: new Date(now - 55 * min).toISOString(),
    first_response_due_at: new Date(now - 25 * min).toISOString(),
    is_first_response_breached: true,
    next_follow_up_at: new Date(now - 25 * min).toISOString(),
    created_at: new Date(now - 55 * min).toISOString(),
    updated_at: new Date(now - 55 * min).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000003',
    lead_code: 'TRV-2026-0003',
    customer_name: 'Ahmed Al-Mansoor',
    customer_email: 'ahmed.m@company.ae',
    customer_phone: '+971501234567',
    customer_city: 'Abu Dhabi',
    customer_country: 'UAE',
    destination: 'Dubai',
    travel_dates: '2026-10-05 to 2026-10-10',
    duration_days: 5,
    pax_adults: 4,
    pax_children: 1,
    pax_infants: 0,
    travel_type: 'luxury',
    budget_range: '$4,500 - $6,000',
    hotel_category: '5-star',
    flight_required: false,
    visa_required: false,
    special_notes: 'Atlantis The Royal stay + VIP Desert Safari with private falconry.',
    source: 'google_ads',
    stage: 'contacted',
    priority: 'high',
    assigned_to: '55555555-5555-5555-5555-555555555555', // Michael
    assigned_at: new Date(now - 3 * hour).toISOString(),
    first_response_due_at: new Date(now - 2.5 * hour).toISOString(),
    first_contacted_at: new Date(now - 2.7 * hour).toISOString(),
    first_response_time_seconds: 1080,
    is_first_response_breached: false,
    next_follow_up_at: new Date(now + 2 * hour).toISOString(),
    last_contacted_at: new Date(now - 2.7 * hour).toISOString(),
    last_activity_type: 'call',
    created_at: new Date(now - 3 * hour).toISOString(),
    updated_at: new Date(now - 2.7 * hour).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000004',
    lead_code: 'TRV-2026-0004',
    customer_name: 'Ananya Patel',
    customer_email: 'ananya.p@yahoo.com',
    customer_phone: '+919820011223',
    customer_city: 'Delhi',
    customer_country: 'India',
    destination: 'Maldives',
    travel_dates: '2026-11-01 to 2026-11-06',
    duration_days: 5,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'honeymoon',
    budget_range: '$3,500 - $5,000',
    hotel_category: 'luxury resort',
    flight_required: true,
    visa_required: false,
    special_notes: 'Water villa with all-inclusive meal plan, seaplane transfer preferred.',
    source: 'referral',
    stage: 'quote_sent',
    priority: 'urgent',
    assigned_to: '55555555-5555-5555-5555-555555555555', // Michael
    assigned_at: new Date(now - 2 * day).toISOString(),
    first_response_due_at: new Date(now - 2 * day).toISOString(),
    first_contacted_at: new Date(now - 2 * day).toISOString(),
    first_response_time_seconds: 620,
    is_first_response_breached: false,
    next_follow_up_at: new Date(now - 1 * day).toISOString(),
    last_contacted_at: new Date(now - 1.2 * day).toISOString(),
    last_activity_type: 'whatsapp',
    created_at: new Date(now - 2 * day).toISOString(),
    updated_at: new Date(now - 1.2 * day).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000005',
    lead_code: 'TRV-2026-0005',
    customer_name: 'Carlos Gomez',
    customer_email: 'cgomez@techcorp.es',
    customer_phone: '+34612345678',
    customer_city: 'Madrid',
    customer_country: 'Spain',
    destination: 'Paris & Italy',
    travel_dates: '2026-10-18 to 2026-10-28',
    duration_days: 10,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'honeymoon',
    budget_range: '$5,000 - $7,000',
    hotel_category: '4-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Colosseum skip-the-line, Eiffel Tower dinner, high speed rail.',
    source: 'website',
    stage: 'in_negotiation',
    priority: 'high',
    assigned_to: '44444444-4444-4444-4444-444444444444', // Emma
    assigned_at: new Date(now - 4 * day).toISOString(),
    first_response_due_at: new Date(now - 4 * day).toISOString(),
    first_contacted_at: new Date(now - 4 * day).toISOString(),
    first_response_time_seconds: 450,
    is_first_response_breached: false,
    next_follow_up_at: new Date(now + 4 * hour).toISOString(),
    last_contacted_at: new Date(now - 18 * hour).toISOString(),
    last_activity_type: 'call',
    created_at: new Date(now - 4 * day).toISOString(),
    updated_at: new Date(now - 18 * hour).toISOString(),
  },
  // WON DEAL 1: Bali Honeymoon (Alex)
  {
    id: 'a1111111-0000-0000-0000-000000000006',
    lead_code: 'TRV-2026-0006',
    customer_name: 'Priya & Vikram Nair',
    customer_email: 'vikram.nair@gmail.com',
    customer_phone: '+919988776655',
    customer_city: 'Bangalore',
    customer_country: 'India',
    destination: 'Bali',
    travel_dates: '2026-10-02 to 2026-10-08',
    duration_days: 6,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'honeymoon',
    budget_range: '$2,800',
    hotel_category: '5-star',
    flight_required: true,
    visa_required: true,
    special_notes: 'Deposit received ($800). Flights and Ayana Resort confirmed.',
    source: 'website',
    stage: 'won',
    priority: 'normal',
    assigned_to: '33333333-3333-3333-3333-333333333333', // Alex
    assigned_at: new Date(now - 6 * day).toISOString(),
    first_contacted_at: new Date(now - 6 * day).toISOString(),
    first_response_time_seconds: 350,
    is_first_response_breached: false,
    last_contacted_at: new Date(now - 1 * day).toISOString(),
    last_activity_type: 'call',
    won_deal_value: 2800,
    package_sale_price: 2800,
    vendor_net_cost: 2240,
    gross_profit: 560,
    profit_margin_pct: 20.0,
    agent_commission_earned: 50.4, // 9% of profit (Silver tier)
    commission_status: 'approved',
    closed_at: new Date(now - 1 * day).toISOString(),
    created_at: new Date(now - 6 * day).toISOString(),
    updated_at: new Date(now - 1 * day).toISOString(),
  },
  // WON DEAL 2: Phuket & Krabi Luxury (Alex)
  {
    id: 'a1111111-0000-0000-0000-000000000011',
    lead_code: 'TRV-2026-0011',
    customer_name: 'Nikhil & Simran Verma',
    customer_email: 'simran.v@gmail.com',
    customer_phone: '+919810012345',
    customer_city: 'Delhi',
    customer_country: 'India',
    destination: 'Thailand',
    travel_dates: '2026-11-01 to 2026-11-08',
    duration_days: 7,
    pax_adults: 2,
    pax_children: 1,
    pax_infants: 0,
    travel_type: 'luxury',
    budget_range: '$4,200',
    hotel_category: '5-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Banyan Tree Phuket pool villa + Phi Phi island speedboat.',
    source: 'referral',
    stage: 'won',
    priority: 'high',
    assigned_to: '33333333-3333-3333-3333-333333333333', // Alex
    assigned_at: new Date(now - 8 * day).toISOString(),
    first_contacted_at: new Date(now - 8 * day).toISOString(),
    first_response_time_seconds: 420,
    won_deal_value: 4200,
    package_sale_price: 4200,
    vendor_net_cost: 3360,
    gross_profit: 840,
    profit_margin_pct: 20.0,
    agent_commission_earned: 75.6, // 9% of profit
    commission_status: 'accrued',
    closed_at: new Date(now - 2 * day).toISOString(),
    created_at: new Date(now - 8 * day).toISOString(),
    updated_at: new Date(now - 2 * day).toISOString(),
  },
  // WON DEAL 3: Swiss Scenic Rails (Emma)
  {
    id: 'a1111111-0000-0000-0000-000000000012',
    lead_code: 'TRV-2026-0012',
    customer_name: 'Arthur & Beatrice Pendelton',
    customer_email: 'b.pendelton@oxford.ac.uk',
    customer_phone: '+447911123456',
    customer_city: 'London',
    customer_country: 'UK',
    destination: 'Switzerland',
    travel_dates: '2026-10-15 to 2026-10-24',
    duration_days: 9,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'luxury',
    budget_range: '$7,500',
    hotel_category: '5-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Glacier Express Excellence Class + Kulm Hotel St. Moritz.',
    source: 'website',
    stage: 'won',
    priority: 'high',
    assigned_to: '44444444-4444-4444-4444-444444444444', // Emma
    assigned_at: new Date(now - 10 * day).toISOString(),
    first_contacted_at: new Date(now - 10 * day).toISOString(),
    first_response_time_seconds: 280,
    won_deal_value: 7500,
    package_sale_price: 7500,
    vendor_net_cost: 6000,
    gross_profit: 1500,
    profit_margin_pct: 20.0,
    agent_commission_earned: 135.0, // 9% of profit
    commission_status: 'paid',
    closed_at: new Date(now - 3 * day).toISOString(),
    created_at: new Date(now - 10 * day).toISOString(),
    updated_at: new Date(now - 3 * day).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000007',
    lead_code: 'TRV-2026-0007',
    customer_name: "David O'Connor",
    customer_email: 'doconnor@irishmail.ie',
    customer_phone: '+353871234567',
    customer_city: 'Dublin',
    customer_country: 'Ireland',
    destination: 'Thailand',
    travel_dates: '2026-11-15 to 2026-11-22',
    duration_days: 7,
    pax_adults: 4,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'budget',
    budget_range: '$800 - $1,000',
    hotel_category: '3-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Expected all-inclusive with flights under $1,000 for 4 people.',
    source: 'meta_ads',
    stage: 'lost',
    priority: 'low',
    assigned_to: '33333333-3333-3333-3333-333333333333',
    assigned_at: new Date(now - 5 * day).toISOString(),
    first_contacted_at: new Date(now - 5 * day).toISOString(),
    first_response_time_seconds: 700,
    is_first_response_breached: false,
    last_contacted_at: new Date(now - 2 * day).toISOString(),
    last_activity_type: 'call',
    lost_reason: 'budget_too_high',
    lost_notes: 'Unrealistic budget for 4 passengers with long-haul flights.',
    closed_at: new Date(now - 2 * day).toISOString(),
    created_at: new Date(now - 5 * day).toISOString(),
    updated_at: new Date(now - 2 * day).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000008',
    lead_code: 'TRV-2026-0008',
    customer_name: 'Marcus Vance',
    customer_email: 'marcus.vance@venture.com',
    customer_phone: '+12125559876',
    customer_city: 'New York',
    customer_country: 'USA',
    destination: 'Japan',
    travel_dates: '2026-11-20 to 2026-12-02',
    duration_days: 12,
    pax_adults: 2,
    pax_children: 1,
    pax_infants: 0,
    travel_type: 'luxury',
    budget_range: '$10,000 - $15,000',
    hotel_category: 'luxury resort',
    flight_required: true,
    visa_required: false,
    special_notes: 'Tokyo, Kyoto private Onsen Ryokan, bullet train green car pass.',
    source: 'website',
    stage: 'new',
    priority: 'urgent',
    assigned_to: null,
    created_at: new Date(now - 10 * min).toISOString(),
    updated_at: new Date(now - 10 * min).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000009',
    lead_code: 'TRV-2026-0009',
    customer_name: 'Sophie Martin',
    customer_email: 'smartin@parisart.fr',
    customer_phone: '+33611223344',
    customer_city: 'Lyon',
    customer_country: 'France',
    destination: 'Greece',
    travel_dates: '2026-10-12 to 2026-10-19',
    duration_days: 7,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'family',
    budget_range: '$3,000 - $4,200',
    hotel_category: '4-star',
    flight_required: true,
    visa_required: false,
    special_notes: 'Santorini sunset cruise + Mykonos beach club reservations.',
    source: 'google_ads',
    stage: 'contacted',
    priority: 'normal',
    assigned_to: '44444444-4444-4444-4444-444444444444',
    assigned_at: new Date(now - 1 * day).toISOString(),
    first_contacted_at: new Date(now - 1 * day).toISOString(),
    first_response_time_seconds: 520,
    is_first_response_breached: false,
    next_follow_up_at: new Date(now + 1 * day).toISOString(),
    last_contacted_at: new Date(now - 6 * hour).toISOString(),
    last_activity_type: 'whatsapp',
    created_at: new Date(now - 1 * day).toISOString(),
    updated_at: new Date(now - 6 * hour).toISOString(),
  },
  {
    id: 'a1111111-0000-0000-0000-000000000010',
    lead_code: 'TRV-2026-0010',
    customer_name: 'Robert Kowalski',
    customer_email: 'robert.k@poltrans.pl',
    customer_phone: '+48601234567',
    customer_city: 'Warsaw',
    customer_country: 'Poland',
    destination: 'Egypt',
    travel_dates: '2026-12-01 to 2026-12-08',
    duration_days: 7,
    pax_adults: 2,
    pax_children: 0,
    pax_infants: 0,
    travel_type: 'adventure',
    budget_range: '$2,500 - $3,500',
    hotel_category: '4-star',
    flight_required: true,
    visa_required: true,
    special_notes: 'Cairo pyramids + 4-night luxury Nile Cruise from Luxor to Aswan.',
    source: 'referral',
    stage: 'in_negotiation',
    priority: 'high',
    assigned_to: '55555555-5555-5555-5555-555555555555',
    assigned_at: new Date(now - 3 * day).toISOString(),
    first_contacted_at: new Date(now - 3 * day).toISOString(),
    first_response_time_seconds: 420,
    is_first_response_breached: false,
    next_follow_up_at: new Date(now + 5 * hour).toISOString(),
    last_contacted_at: new Date(now - 12 * hour).toISOString(),
    last_activity_type: 'call',
    created_at: new Date(now - 3 * day).toISOString(),
    updated_at: new Date(now - 12 * hour).toISOString(),
  },
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'f1111111-0000-0000-0000-000000000001',
    lead_id: 'a1111111-0000-0000-0000-000000000004',
    assigned_to: '55555555-5555-5555-5555-555555555555',
    title: 'Call to discuss water villa upgrade options',
    scheduled_at: new Date(now - 1 * day).toISOString(),
    channel: 'call',
    priority: 'urgent',
    status: 'missed',
    notes: 'Client was waiting for husband to review Maldives seaplane times',
    created_at: new Date(now - 2 * day).toISOString(),
  },
  {
    id: 'f1111111-0000-0000-0000-000000000002',
    lead_id: 'a1111111-0000-0000-0000-000000000005',
    assigned_to: '44444444-4444-4444-4444-444444444444',
    title: 'Send revised Paris hotel quote with balcony view',
    scheduled_at: new Date(now + 4 * hour).toISOString(),
    channel: 'whatsapp',
    priority: 'high',
    status: 'pending',
    notes: 'Customer requested 4-star hotel closer to metro line 1',
    created_at: new Date(now - 18 * hour).toISOString(),
  },
  {
    id: 'f1111111-0000-0000-0000-000000000003',
    lead_id: 'a1111111-0000-0000-0000-000000000003',
    assigned_to: '55555555-5555-5555-5555-555555555555',
    title: 'Confirm Desert Safari private car availability',
    scheduled_at: new Date(now + 2 * hour).toISOString(),
    channel: 'call',
    priority: 'high',
    status: 'pending',
    notes: 'Check if land cruiser can pick up from Dubai Marina hotel',
    created_at: new Date(now - 2.7 * hour).toISOString(),
  },
  {
    id: 'f1111111-0000-0000-0000-000000000004',
    lead_id: 'a1111111-0000-0000-0000-000000000010',
    assigned_to: '55555555-5555-5555-5555-555555555555',
    title: 'Follow up on Nile cruise cabin preference',
    scheduled_at: new Date(now + 5 * hour).toISOString(),
    channel: 'email',
    priority: 'normal',
    status: 'pending',
    notes: 'Upper deck cabin option quoted',
    created_at: new Date(now - 12 * hour).toISOString(),
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-001',
    lead_id: 'a1111111-0000-0000-0000-000000000003',
    agent_id: '55555555-5555-5555-5555-555555555555',
    activity_type: 'call',
    title: 'Initial Consultation Call',
    outcome: 'Interested',
    notes: 'Spoke with Mr. Ahmed. Very keen on Atlantis The Royal for 5 nights. Traveling with family (4 adults, 1 child). Sent preliminary options.',
    call_duration_seconds: 380,
    created_at: new Date(now - 2.7 * hour).toISOString(),
  },
  {
    id: 'act-002',
    lead_id: 'a1111111-0000-0000-0000-000000000004',
    agent_id: '55555555-5555-5555-5555-555555555555',
    activity_type: 'whatsapp',
    title: 'Sent Maldives PDF Quote',
    outcome: 'Quote Sent',
    notes: 'Shared detailed PDF itinerary with Adaaran Prestige Vadoo and Sun Siyam Olhuveli.',
    created_at: new Date(now - 1.2 * day).toISOString(),
  },
  {
    id: 'act-003',
    lead_id: 'a1111111-0000-0000-0000-000000000005',
    agent_id: '44444444-4444-4444-4444-444444444444',
    activity_type: 'call',
    title: 'Negotiation Call on Europe Rail Passes',
    outcome: 'Call Back Later',
    notes: 'Discussed Eurail Pass vs Point-to-Point tickets. Carlos prefers high-speed Frecciarossa tickets. Will email revised quote today.',
    call_duration_seconds: 420,
    created_at: new Date(now - 18 * hour).toISOString(),
  },
  {
    id: 'act-004',
    lead_id: 'a1111111-0000-0000-0000-000000000006',
    agent_id: '33333333-3333-3333-3333-333333333333',
    activity_type: 'stage_change',
    title: 'Deal Won - Deposit Received',
    outcome: 'Won',
    notes: 'Client made initial deposit of $800. Sale: $2,800, Net Vendor Cost: $2,240, Profit: $560 (20% margin). Commission: $50.40.',
    created_at: new Date(now - 1 * day).toISOString(),
  },
];

export const INITIAL_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-1',
    name: 'Initial Welcome & Trip Inquiry',
    category: 'welcome',
    message_body: 'Hi {{customer_name}}, thank you for reaching out to Wanderlust Travel! ✈️ This is {{agent_name}}, your dedicated travel planner for {{destination}}. I saw your inquiry for a {{pax_count}} trip. Could you let me know if your travel dates are flexible so I can send the best hotel options?',
    is_active: true,
    created_at: new Date(now - 10 * day).toISOString(),
  },
  {
    id: 'tpl-2',
    name: 'Custom Itinerary & Quote Sent',
    category: 'quote_followup',
    message_body: 'Hello {{customer_name}}! 🌴 I have prepared a customized itinerary for your {{destination}} holiday. I have emailed the full PDF and price breakdown. Have you had a chance to review it? I can also adjust the resort or activities according to your preference.',
    is_active: true,
    created_at: new Date(now - 10 * day).toISOString(),
  },
  {
    id: 'tpl-3',
    name: 'Urgent Special Price Lock',
    category: 'discount',
    message_body: 'Hi {{customer_name}}, quick update! 🌟 The airline and resort in {{destination}} currently have a 15% discount valid for the next 48 hours. If we lock it in today, we can save you approximately $350 on your package. Would you like to proceed with the reservation?',
    is_active: true,
    created_at: new Date(now - 10 * day).toISOString(),
  },
  {
    id: 'tpl-4',
    name: 'Visa & Travel Documents Check',
    category: 'reminder',
    message_body: 'Hi {{customer_name}}, just checking in regarding the visa requirements for {{destination}}. We provide complimentary visa document verification. Let me know when is a good time for a quick 5-minute call today!',
    is_active: true,
    created_at: new Date(now - 10 * day).toISOString(),
  },
];

export const INITIAL_SLA: SlaSettings = {
  id: 'sla-default',
  // SLA & Business Hours
  frt_minutes: 30,
  overdue_grace_minutes: 60,
  escalate_to_manager: true,
  auto_reassign_breached_leads: false,
  auto_reassign_hours: 4,
  business_hours_start: '09:00',
  business_hours_end: '18:00',
  freeze_sla_weekends: true,
  timezone: 'America/New_York (EST)',
  pre_breach_warning_minutes: 15,

  // Routing Engine
  routing_strategy: 'workload_balanced',
  routing_overflow_policy: 'unassigned_pool',
  vip_high_budget_threshold: 8000,
  vip_route_seniors_only: true,
  lead_cooldown_minutes: 3,

  // Currency & Financials
  currency: 'USD',
  currency_symbol: '$',
  date_format: 'DD/MM/YYYY',
  commission_tds_pct: 10,
  min_gross_margin_threshold: 12,
  payout_frequency: 'monthly',

  // Audio & Notifications
  notification_sound_enabled: true,
  notification_sound_preset: 'chime',
  notification_volume: 75,
  mute_sound_in_call: true,
  browser_push_enabled: false,
  toast_duration_seconds: 3,

  // Taxonomies
  custom_lost_reasons: [
    'Budget Mismatch (Customer expectations unrealistic)',
    'Booked with Competitor (Price/package comparison)',
    'Trip Postponed or Cancelled',
    'Unresponsive after 3+ Follow-ups',
    'Visa Denied / Passport Issue',
    'Flight Fares Surged beyond budget',
    'Destination Safety or Weather Advisory',
    'Other / Custom Reason',
  ],
  custom_lead_sources: [
    'website',
    'meta_ads',
    'google_search',
    'referral',
    'walk_in',
    'ota_partner',
    'b2b_subagent',
    'instagram_dm',
  ],
  auto_archive_days: 30,
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: '33333333-3333-3333-3333-333333333333',
    title: 'New High-Priority Lead Assigned',
    message: 'Rohan Sharma has requested a Bali honeymoon package ($2k - $3k). SLA response due in 16 mins!',
    type: 'lead_assigned',
    link: '/leads/a1111111-0000-0000-0000-000000000001',
    is_read: false,
    created_at: new Date(now - 14 * min).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: '44444444-4444-4444-4444-444444444444',
    title: '⚠️ SLA First Response Breached!',
    message: 'Jessica Taylor (Switzerland family ski trip) has not been contacted within 30 minutes.',
    type: 'sla_breach',
    link: '/leads/a1111111-0000-0000-0000-000000000002',
    is_read: false,
    created_at: new Date(now - 25 * min).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: '22222222-2222-2222-2222-222222222222',
    title: 'Manager Alert: SLA Breach on Team Europe',
    message: 'Agent Emma Watson has an uncontacted lead past the 30-minute threshold.',
    type: 'sla_breach',
    link: '/leads/a1111111-0000-0000-0000-000000000002',
    is_read: false,
    created_at: new Date(now - 25 * min).toISOString(),
  },
  {
    id: 'notif-4',
    user_id: '55555555-5555-5555-5555-555555555555',
    title: 'Overdue Follow-up Reminder',
    message: 'Ananya Patel (Maldives quote) follow-up was due yesterday. Please contact customer today.',
    type: 'follow_up_due',
    link: '/leads/a1111111-0000-0000-0000-000000000004',
    is_read: false,
    created_at: new Date(now - 1 * day).toISOString(),
  },
];
